### ISSUE TITLE
swagger2openapi: connection issues when using http2

### ISSUE THREAD

**Issue by pderaaij** [Mermade/oas-kit#148]
### Detailed Description
When I try to run `swagger2openapi` on one of our online definitions I get the following error:

```bash
internal/http2/util.js:476
      throw new ERR_HTTP2_INVALID_CONNECTION_HEADERS(key);
      ^

TypeError [ERR_HTTP2_INVALID_CONNECTION_HEADERS]: HTTP/1 Connection specific headers are forbidden: "connection"
    at mapToHeaders (internal/http2/util.js:476:13)
    at ClientHttp2Session.request (internal/http2/core.js:1480:25)
    at HttpRequestManager.makeHttp2Request (/Users/p.deraaij/projects/api-testing/node_modules/http2-client/lib/request.js:413:30)
    at HttpRequestManager.makeRequest (/Users/p.deraaij/projects/api-testing/node_modules/http2-client/lib/request.js:344:21)
    at HttpRequestManager.onIdentification (/Users/p.deraaij/projects/api-testing/node_modules/http2-client/lib/request.js:279:24)
    at HttpRequestManager.onIdentify (/Users/p.deraaij/projects/api-testing/node_modules/http2-client/lib/request.js:379:9)
    at TLSSocket.onConnect (/Users/p.deraaij/projects/api-testing/node_modules/http2-client/lib/request.js:450:9)
    at Object.onceWrapper (events.js:276:13)
    at TLSSocket.emit (events.js:188:13)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1167:10)
```

I've traced it down to a difference between `node-fetch-h2` and `http2-client`. 

http2-client removes the `connection` header while creating a HTTP2 request. However, `node-fetch-h2` adds a `Connection` header, note the capital C. As a result the HTTP2 request is made with a Connection header which is invalid.

The reason `node-fetch-h2` adds a Connection header is due to two reasons:

1. There is no connection header already
2. No agent is defined on the request.

If s2o is used by `oas-resolver` it does define an agent and therefore doesn't throw this issue. Swagger2openapi doesn't do that by default.

So, either this should be fixed by one of the two dependencies or swagger2open should by default use an agent. The latter option feels valid, but curious to other opinions.

**Comment by MikeRalphson** [comment]
If `http2-client` only removes a `connection` header if it is all lower-case, I think that's a bug in that package, as header names are (obviously) case-insensitive.

**Comment by pderaaij** [comment]
For reference, solved in:

https://github.com/hisco/http2-client/pull/11/files

Will be fixed by upgrading to `1.3.2` of http2-client.

**Comment by MikeRalphson** [comment]
Thanks for nailing this down.

**Comment by MikeRalphson** [comment]
Dependencies ~~hacked~~ updated. I'm in two minds about adding a test-case involving a local http2 server to prevent regressions here. What do you think?

**Comment by pderaaij** [comment]
It could be interesting to add, I do no see problems with it. What is it that has you on two minds about it?

**Comment by MikeRalphson** [comment]
Just how realistic a test it would be with a minimal local http2 server, but I guess it can't hurt to have something there.

**Comment by pderaaij** [comment]
Well, even with a light mocking server you can test a connection cycle. Any regression on header/connection level + response headers will be found.

**Comment by MikeRalphson** [comment]
Successfully published:
 - oas-linter@3.0.1
 - oas-resolver@2.2.1
 - oas-validator@3.2.1
 - reftools@1.0.7
 - swagger2openapi@5.2.1
