### ISSUE TITLE
recurse function can recurse infinitely

### ISSUE THREAD

**Issue by jdmurphy** [Mermade/oas-kit#87]
### Checklist

- [x] Conversion: I have checked my source definition is valid OpenAPI 2.0

### Detailed Description
When a valid OpenAPI 2.0 spec contains a definition which is self-referencing, the recurse function will go on forever (well, until the stack runs out) due to the fact that it has no maxDepth functionality. There needs to be some way like tracking maxDepth or recognizing that it is in an infinite recursion to break out.

Simple valid OpenAPI 2.0 spec illustrating issue:
```json
{
  "info": {
    "title": "Example title",
    "description": "Example description.",
    "version": "v1"
  },
  "swagger": "2.0",
  "produces": [
    "application/xml",
    "application/json",
    "application/octet-stream",
    "text/plain"
  ],
  "host": "example.org",
  "basePath": "/example/v1",
  "schemes": [
    "https"
  ],
  "tags": [
    {
      "name": "examples",
      "description": "Operations about examples"
    }
  ],
  "paths": {
    "/examples": {
      "post": {
        "summary": "Create an example",
        "description": "Create an example using a POST request",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Example",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Example"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Bad Request"
          }
        },
        "tags": [
          "examples"
        ],
        "operationId": "postExample"
      }
    }
  },
  "definitions": {
    "Example": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "sub_examples": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Example"
          }
        }
      },
      "required": [
        "id",
        "sub_examples"
      ],
      "description": "Create an example"
    }
  }
}
```

**Comment by MikeRalphson** [comment]
What options are you using? The recourse function doesn't follow `$ref`s, so this should not be a problem.

**Comment by jdmurphy** [comment]
@MikeRalphson, we are using the converter directly as described in the README of widdershins with:

* codeSamples: true
* language_tabs: [{ ruby: 'ruby' }, { shell: 'shell' }]
* lang: true
* tocSummary: true

along with our own templates and callback function. Is there an option we are missing?

**Comment by MikeRalphson** [comment]
OK, makes sense that it may be an issue in widdershins with the use of this library, rather than a bug in the `recurse` function.

**Comment by jdmurphy** [comment]
@MikeRalphson, I got mostly the same error, but for some reason it doesn't show the `sampler` for me. I get `(node:48208) UnhandledPromiseRejectionWarning: Maximum call stack size exceeded` If the sampler is what is causing it, then that is good information and I can go log an issue or a PR to that project, I just wasn't getting that information from my output.

**Comment by MikeRalphson** [comment]
Ok, that's interesting. Was there a traceback?

**Comment by jdmurphy** [comment]
What I see is:

```
(node:48208) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at String.split (<anonymous>)
    at jpescape (/Users/jdmurphy/Documents/git/openapi-docs/node_modules/reftools/lib/jptr.js:9:11)
    at recurse (/Users/jdmurphy/Documents/git/openapi-docs/node_modules/reftools/lib/recurse.js:34:60)
    at recurse (/Users/jdmurphy/Documents/git/openapi-docs/node_modules/reftools/lib/recurse.js:51:13)
```
The last line is then repeated for the rest of the stack trace.

**Comment by MikeRalphson** [comment]
Still can't reproduce this. Can you confirm your `widdershins` version number, and that you aren't using the `recurse` function directly in your callback function or templates?

**Comment by MikeRalphson** [comment]
I'm afraid I can't reproduce the issue with `widdershins` `v3.4.2` and the example you have posted above.
