### ISSUE TITLE
packages.json doesn't reference `node-fetch`

### ISSUE THREAD

**Issue by jkaster** [Mermade/oas-kit#89]
After cloning and doing `npm i` I still get a failure on the require for `node-fetch`. Here's the command-line and stack trace:

```bash
node ./oas-kit/packages/swagger2openapi/swagger2openapi.js -o spec.v3.json spec.json
module.js:538
    throw err;
    ^

Error: Cannot find module 'node-fetch'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/me/oas-kit/packages/swagger2openapi/index.js:9:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```
#### Other stuff

I'm using the current build, found it from https://github.com/OAI/OpenAPI-Specification/blob/master/IMPLEMENTATIONS.md

**Comment by jkaster** [comment]
Ah .. I may need to run `npm i` in the `swagger2openapi` folder also.

**Comment by jkaster** [comment]
yup, that was the problem. 

It would be good to have the node installs covered by some prepare script in the root folder, but that's minor.
